-- --#################INSERTING DATA INTO BUS#############################
INSERT INTO BUS
(ID, BUSINESS_ID, NAME)
VALUES
  (S_BUS.NEXTVAL, '24_1', 'MyBus1')
/

INSERT INTO BUS
(ID, BUSINESS_ID, NAME)
VALUES
  (S_BUS.NEXTVAL, '9_1', 'MyBus2')
/
-- --#################END INSERTING DATA INTO BUS#############################

-- --#################INSERTING DATA INTO TRIP#################################

INSERT INTO TRIP
(ID, BUS_ID, TRIP_ID)
VALUES
  (S_TRIP.NEXTVAL, '24_1', 'qwertyu')
/

INSERT INTO TRIP
(ID, BUS_ID, TRIP_ID)
VALUES
  (S_TRIP.NEXTVAL, '9_1', 'asdfghjk')
/
-- --#################END INSERTING DATA INTO TRIP#############################

-- --#################INSERTING DATA INTO BUS_LOCATION_UPDATE#################################

INSERT INTO BUS_LOCATION_UPDATE
(ID, LAST_UPDATE, TRIP_ID, LATITUDE, LONGITUDE)
VALUES
(S_BUS_LOCATION_UPDATE.NEXTVAL, TO_TIMESTAMP('5/5/2020 12:00:00.000000 AM', 'fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'qwertyu', 100.2, 200.3)
/

INSERT INTO BUS_LOCATION_UPDATE
(ID, LAST_UPDATE, TRIP_ID, LATITUDE, LONGITUDE)
VALUES
  (S_BUS_LOCATION_UPDATE.NEXTVAL, TO_TIMESTAMP('5/5/2021 12:00:00.000000 AM', 'fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'qwertyu', 100.5, 210.6)
/

--#################END INSERTING DATA INTO BUS_LOCATION_UPDATE##############################
