-- --#################INSERTING DATA INTO BUS_LOCATION_UPDATE#################################

INSERT INTO BUS_LOCATION_UPDATE
  (ID, LAST_UPDATE, NAME)
VALUES
  (S_BUS_LOCATION_UPDATE.NEXTVAL, TO_TIMESTAMP('5/5/2020 12:00:00.000000 AM', 'fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'TASK_DEFINITION')
/

INSERT INTO BUS_LOCATION_UPDATE
  (ID, LAST_UPDATE, NAME)
VALUES
  (S_BUS_LOCATION_UPDATE.NEXTVAL, TO_TIMESTAMP('5/5/2021 12:00:00.000000 AM', 'fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'JOB_DEFINITION')
/

--#################END INSERTING DATA INTO BUS_LOCATION_UPDATE##############################
